services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Montar código fuente como volumen
      - gem_cache:/gems # Cachear gems entre reinicios
    environment:
      - DATABASE_URL=mysql2://root:password@db/daitov_admin
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:11.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: daitov_admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  gem_cache:
  db_data:
