ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    default-mysql-client \
    default-libmysqlclient-dev \
    git \
    libvips \
    libyaml-dev \
    nodejs \
    vim && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH="/gems" \
    BUNDLE_APP_CONFIG="/gems" \
    GEM_HOME="/gems" \
    PATH="${PATH}:/gems/bin:/app/bin"

RUN mkdir -p /gems /app
WORKDIR /app

COPY bin/docker-entrypoint-dev /usr/local/bin/
COPY bin bin/
COPY config/credentials.yml.enc config/credentials.yml.enc
COPY . .
RUN chmod +x /usr/local/bin/docker-entrypoint-dev
ENTRYPOINT ["docker-entrypoint-dev"]

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
